version: '3.7'
services:

  guild_grpc_mongo:
    image: mongo:${MONGO_VERSION}
    container_name: mongo-db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_GUILD_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PW}
      MONGO_GUILD_USER: ${MONGO_GUILD_USER}
      MONGO_GUILD_PW: ${MONGO_GUILD_PW}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      - ${PWD}/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks: 
      - guild_grpc_network

  guild_grpc_booking_service:
    deploy:
     resources:
       limits:
         cpus: '0.5'
         memory: '512M'
    restart: on-failure
    build:
      context: ../booking
      dockerfile: Dockerfile
    container_name: booking-service
    ports:
      - "8082:8082"
      - "9090:9090"
    depends_on:
      - guild_grpc_mongo
    environment:
      - SPRING_DATA_MONGODB_host=mongo-db
    networks: 
      - guild_grpc_network

  guild_grpc_vehicle_service:
    deploy:
     resources:
       limits:
         cpus: '0.5'
         memory: '512M'
    container_name: vehicle-service
    restart: on-failure
    build:
      context: ../vehicle
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
      - "50051:50052"
      - "8082:8080"
    environment:
      - CAR_FLEET_SIZE: 3000
      - BICYCLE_FLEET_SIZE: 1500
      - MOTORCYCLE_FLEET_SIZE: 500
      - LOCALIZATION_SERVER_URL: http://[::1]:50052
      - BOOKING_SERVICE_EXPOSED_PORT: 50051
      - LOCALIZATION_PING_INTERVAL: 60
      - FUEL_CONSUME_PER_TURN: 2.0
    networks: 
      - guild_grpc_network

  guild_grpc_localization_service:
    deploy:
     resources:
       limits:
         cpus: '0.5'
         memory: '512M'
    container_name: localization-service
    restart: on-failure
    build:
      context: ../localization
      dockerfile: Dockerfile
    ports:
      - "50052:50051"
      - "8081:8081"
    environment:
      - MONGODB_URI:mongodb://root-user:root-pw@localhost:27017/
    networks: 
      - guild_grpc_network

volumes:
  mongodb_data_container: {}
  
networks:
  guild_grpc_network:
    driver: bridge