spring:
  application:
    name: booking
  data:
    mongodb:
      host: localhost
      port: 27017
      database: guild-grpc-db
      authentication-database: guild-grpc-db
      password: guild-grpc-password
      username: guild-grpc-user

grpc:
  server:
    port: 9090
  client:
    vehicle:
      address: localhost:9091
      negotiation-type: plaintext

server:
  port: 8082
rest:
  service:
    vehicle:
      url: http://localhost:8080

logging:
  level:
    root: WARN
    org.springframework.web: ERROR
    it.pagopa.guild.grpc.booking: DEBUG
  file:
    name: logs/booking.log
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"
    file: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"

